### ISSUE TITLE
Why? Isn't there a stdlib for yaml parsing?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/gamble#1]
The readme mentions "for libyaml" - is this correct? Why have a dependency on a system library? Sorry if I'm confused.

**Comment by vito** [comment]
There's no stdlib; there are various packages though. We've been using goyaml (launchpad.net/goyaml) in most places, but it's LGPL which is a bit fishy given that Go is all statically linked. (Also it's on launchpad so getting it takes half an hour.) The rest are abandoned and/or not close to done, last I checked.

**Comment by drnic** [comment]
Ah goyaml was what I was thinking of.

I understand re licenses that might bleed into our codes.

Gamble is pure Go; or going to require libyaml installed? What will we do for Windows?

**Comment by tjarratt** [comment]
@drnic Gamble is currently only a wrapper around libyaml, so it's Go + a statically linked c library.  We're hoping to avoid requiring libyaml being installed, but now that we have installers, maybe we can distribute the dylib as well. 

I've heard a rumour that it's possible to cross compile cgo on windows, even though the compiler normally disallows that.

**Comment by tedsuo** [comment]
go can statically compile C into the same binary.  Our goal is to build natively on each target architecture, and still distribute a single binary.

**Comment by drnic** [comment]
The libyaml will be statically compiled in? Ok cool.

**Comment by tjarratt** [comment]
We've got this statically linked in the go cli, so it seems safe to close this issue. 

The one thing we need to do is document the process and write some blog posts. There's some FUD in the go community around static linking and C Go, so it would be nice to share this and get more feedback.

**Comment by drnic** [comment]
Good idea about following up on the static linking stuff.
